name: elixir-workflow
on: [pull_request, push]
jobs:
  run-elixir-tests:
    name: run-elixir-tests
    runs-on: macos-11
    steps:
      - name: run-tests
        uses: mileschou/elixir-action@master
        with:
          args: mix test
